# Generated by Django 4.1.2 on 2022-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=50, verbose_name='连锁公司ID')),
                ('branch_name', models.CharField(max_length=80, verbose_name='连锁公司')),
                ('operational_region', models.CharField(max_length=80, verbose_name='营业大区ID')),
                ('operational_region_desc', models.CharField(max_length=250, verbose_name='营业大区')),
                ('mession_target', models.IntegerField(verbose_name='任务目标')),
                ('sdate', models.DateField(verbose_name='日期')),
            ],
        ),
    ]
