# Generated by Django 4.1.2 on 2022-11-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmession',
            name='operational_region',
        ),
        migrations.RemoveField(
            model_name='regionmession',
            name='operational_region_desc',
        ),
        migrations.AddField(
            model_name='regionmession',
            name='main_attribute',
            field=models.CharField(default='asd', max_length=120, verbose_name='主推名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionmession',
            name='org_department_id',
            field=models.CharField(default='123', max_length=80, verbose_name='营业部ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionmession',
            name='org_department_name',
            field=models.CharField(default='123', max_length=250, verbose_name='营业部'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionmession',
            name='satnr',
            field=models.CharField(default='123', max_length=80, verbose_name='商品代码'),
            preserve_default=False,
        ),
    ]
