# Generated by Django 4.1.2 on 2022-11-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_regionmession_operational_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmession',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='regionmession',
            name='org_department_id',
        ),
    ]
