# Generated by Django 4.1.2 on 2022-11-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_regionmession_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmession',
            name='mession_target',
            field=models.FloatField(verbose_name='任务目标'),
        ),
    ]
