# Generated by Django 4.1.2 on 2022-12-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_regionmession_mession_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=80, verbose_name='连锁公司ID')),
                ('satnr', models.CharField(max_length=80, verbose_name='商品代码')),
                ('main_attribute', models.CharField(max_length=120, verbose_name='主推名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
