# Generated by Django 4.1.2 on 2023-01-07 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_mainattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreComparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='门店ID')),
                ('is_comparable', models.CharField(max_length=10, verbose_name='是否可比店')),
                ('create_time', models.DateTimeField(default='2023-01-07 14:05:51', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default='2023-01-07 14:05:51', verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='create_time',
            field=models.DateTimeField(default='2023-01-07 14:05:51', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='modify_time',
            field=models.DateTimeField(default='2023-01-07 14:05:51', verbose_name='修改时间'),
        ),
    ]
