# Generated by Django 4.1.2 on 2023-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_mainattribute_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(verbose_name='日期')),
                ('holiday', models.CharField(max_length=40, verbose_name='节假日')),
                ('promotion_event', models.CharField(max_length=80, verbose_name='促销活动')),
                ('promotion_level', models.CharField(max_length=10, verbose_name='活动等级')),
            ],
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='create_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='modify_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='storecomparable',
            name='create_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storecomparable',
            name='modify_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='storemapping',
            name='create_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storemapping',
            name='modify_time',
            field=models.DateTimeField(default='2023-03-21 13:20:40', verbose_name='修改时间'),
        ),
    ]
