# Generated by Django 4.1.2 on 2023-05-04 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_alter_mainattribute_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='门店ID')),
                ('create_time', models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='修改时间')),
            ],
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='create_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='modify_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='storecomparable',
            name='create_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storecomparable',
            name='modify_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='storemapping',
            name='create_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storemapping',
            name='modify_time',
            field=models.DateTimeField(default='2023-05-04 08:52:11', verbose_name='修改时间'),
        ),
    ]
