# Generated by Django 4.1.2 on 2023-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('create_time', models.DateTimeField(default='2023-05-26 10:25:40', verbose_name='创建时间')),
            ],
        ),
    ]
