# Generated by Django 4.1.2 on 2024-06-24 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app03", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=40, verbose_name="连锁公司")),
                ("sdate_md", models.CharField(max_length=20, verbose_name="日期（月日）")),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=40, verbose_name="渠道")),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDtl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=240, verbose_name="门店名称")),
                ("vip_name", models.CharField(max_length=240, verbose_name="会员名称")),
                (
                    "classification_zhonglei_desc",
                    models.CharField(max_length=240, verbose_name="自定义中分类"),
                ),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvinceSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province_name", models.CharField(max_length=120, verbose_name="省份")),
                ("year_desc", models.CharField(max_length=20, verbose_name="年份")),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreTop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=240, verbose_name="门店名称")),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification_dalei_desc",
                    models.CharField(max_length=80, verbose_name="自定义大类"),
                ),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                ("business_amount_corr", models.FloatField(verbose_name="同期营业额")),
                ("business_profit", models.FloatField(verbose_name="毛利率")),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VipNums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_name", models.CharField(max_length=80, verbose_name="会员等级")),
                ("business_amount", models.FloatField(verbose_name="营业额")),
                (
                    "total_vip_num",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="人数",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default="2024-06-24 16:15:14", verbose_name="创建时间"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GptAnswer",
        ),
    ]
